<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsq7s4b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsq7s4b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWsq7s4b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWsq7s4b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWsq7s4b\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wsq7s4b',
    'container.build_id' => 'fb069223',
    'container.build_time' => 1534057147,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsq7s4b');
